spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: votingAgenda
  mvc:
    locale: en_US
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
