spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/agendaVoting}
      auto-index-creation: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
cpf-consult:
  url: ${CPF_CONSULT_URL:https://user-info.herokuapp.com/users/}
